name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install deps and build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v6
        with:
          path: dist/*
